platform :ios, '12.0'
use_frameworks!

target 'RSRealmHelper_Example' do
    pod 'RSRealmHelper', :path => '../'

    target 'RSRealmHelper_Tests' do
        inherit! :search_paths

    
    end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if Gem::Version.new('8.0') > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
      end
    end
  end
end
